name:                haskell-snake
version:             0.1.0.0
github:              "Alex1005a/haskell-snake"
license:             BSD3
author:              "Alex1005a"
maintainer:          "asafofalexander@gmail.com"
copyright:           "2022 Alex1005a"

extra-source-files:
- README.md
- CHANGELOG.md

data-files:
  assets/*.bmp

description:         Please see the README on GitHub at <https://github.com/Alex1005a/haskell-snake#readme>

dependencies:
- base >= 4.7 && < 5
- linear
- relude
- random
- mtl
- microlens-th
- websockets
- network
- cereal

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions: NoImplicitPrelude

executables:
  snake-sdl2-exe:
    default-extensions: NoImplicitPrelude 
    main:                Main.hs
    source-dirs:         sdl2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-snake
    - sdl2
  snake-ansi-exe:
    default-extensions: NoImplicitPrelude 
    main:                Main.hs
    source-dirs:         terminal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-snake
    - ansi-terminal-game

tests:
  haskell-snake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-snake
